# Site settings
title: Software Engineer
email: desmond.appiah@gmail.com
description: Keeping track of a few reflections and what goes on in hammock zones
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.dappiahkubi.com" # the base hostname & protocol for your site
twitter_username: sir_desmond
github_username:  sirdesmond

# Build settings
markdown: kramdown
